[tool.poetry]
name = "nonebot-plugin-fun-content"
version = "0.1.0"
description = "从多个 API 获取趣味内容，如一言、土味情话、舔狗日记等。"
authors = ["Chensiyu <rk.chensiyu@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
httpx = "^0.23.0"
nonebot2 = "^2.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
